# Source : https://github.com/nodematiclabs/github-actions-gcp-demo/blob/main/.github/workflows/build-and-deploy.yaml
name: Deploy_app

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v4'
    
    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        workload_identity_provider: https://iam.googleapis.com/projects/1065734788598/locations/global/workloadIdentityPools/github/providers/my-repo

      

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'


    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev
        docker build -t europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/demo/Deploy:latest .
        docker push europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/demo/Deploy:latest

# pas configguer gke pour l instant
#    - name: deploy to gke
#      env:
#        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
#      run: |
#        gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
#        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
#        kubectl apply -f resources.yaml